
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://test/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://test/", className = "client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://test/", className = "client.SayHelloResponse")
    @Action(input = "http://test/HelloService/sayHelloRequest", output = "http://test/HelloService/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayGoodbye", targetNamespace = "http://test/", className = "client.SayGoodbye")
    @ResponseWrapper(localName = "sayGoodbyeResponse", targetNamespace = "http://test/", className = "client.SayGoodbyeResponse")
    @Action(input = "http://test/HelloService/sayGoodbyeRequest", output = "http://test/HelloService/sayGoodbyeResponse")
    public String sayGoodbye(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
