
package info.student;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentInfo", targetNamespace = "http://student.info/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentInfo {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://student.info/", className = "info.student.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://student.info/", className = "info.student.GetNameResponse")
    @Action(input = "http://student.info/StudentInfo/getNameRequest", output = "http://student.info/StudentInfo/getNameResponse")
    public String getName();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAge", targetNamespace = "http://student.info/", className = "info.student.GetAge")
    @ResponseWrapper(localName = "getAgeResponse", targetNamespace = "http://student.info/", className = "info.student.GetAgeResponse")
    @Action(input = "http://student.info/StudentInfo/getAgeRequest", output = "http://student.info/StudentInfo/getAgeResponse")
    public int getAge();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudentInfo", targetNamespace = "http://student.info/", className = "info.student.GetStudentInfo")
    @ResponseWrapper(localName = "getStudentInfoResponse", targetNamespace = "http://student.info/", className = "info.student.GetStudentInfoResponse")
    @Action(input = "http://student.info/StudentInfo/getStudentInfoRequest", output = "http://student.info/StudentInfo/getStudentInfoResponse")
    public String getStudentInfo();

}
