
package info.student;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentInfoService", targetNamespace = "http://student.info/", wsdlLocation = "http://localhost:8077/StudentInfo?wsdl")
public class StudentInfoService
    extends Service
{

    private final static URL STUDENTINFOSERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTINFOSERVICE_EXCEPTION;
    private final static QName STUDENTINFOSERVICE_QNAME = new QName("http://student.info/", "StudentInfoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8077/StudentInfo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTINFOSERVICE_WSDL_LOCATION = url;
        STUDENTINFOSERVICE_EXCEPTION = e;
    }

    public StudentInfoService() {
        super(__getWsdlLocation(), STUDENTINFOSERVICE_QNAME);
    }

    public StudentInfoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTINFOSERVICE_QNAME, features);
    }

    public StudentInfoService(URL wsdlLocation) {
        super(wsdlLocation, STUDENTINFOSERVICE_QNAME);
    }

    public StudentInfoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTINFOSERVICE_QNAME, features);
    }

    public StudentInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentInfoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentInfo
     */
    @WebEndpoint(name = "StudentInfoPort")
    public StudentInfo getStudentInfoPort() {
        return super.getPort(new QName("http://student.info/", "StudentInfoPort"), StudentInfo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentInfo
     */
    @WebEndpoint(name = "StudentInfoPort")
    public StudentInfo getStudentInfoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://student.info/", "StudentInfoPort"), StudentInfo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTINFOSERVICE_EXCEPTION!= null) {
            throw STUDENTINFOSERVICE_EXCEPTION;
        }
        return STUDENTINFOSERVICE_WSDL_LOCATION;
    }

}
